package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "CloseApproachData",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://ssd-api.jpl.nasa.gov",
			"auth": map[string]any{
				"prefix": "Bearer",
			},
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"cadapi": map[string]any{},
			},
		},
		"entity": map[string]any{
			"cadapi": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "count",
						"req": true,
						"type": "`$NUMBER`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "data",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "field",
						"req": false,
						"type": "`$ARRAY`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "signature",
						"req": true,
						"type": "`$OBJECT`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "total",
						"req": false,
						"type": "`$NUMBER`",
						"active": true,
						"index$": 4,
					},
				},
				"name": "cadapi",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"example": "Earth",
											"kind": "query",
											"name": "body",
											"orig": "body",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "ATE",
											"kind": "query",
											"name": "class",
											"orig": "class",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "comet",
											"orig": "comet",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "2100-01-01",
											"kind": "query",
											"name": "date_max",
											"orig": "date_max",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "2018-01-01",
											"kind": "query",
											"name": "date_min",
											"orig": "date_min",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "433",
											"kind": "query",
											"name": "des",
											"orig": "des",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "diameter",
											"orig": "diameter",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "0.2",
											"kind": "query",
											"name": "dist_max",
											"orig": "dist_max",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "0.05",
											"kind": "query",
											"name": "dist_min",
											"orig": "dist_min",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "fullname",
											"orig": "fullname",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "h_max",
											"orig": "h_max",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "h_min",
											"orig": "h_min",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "kind",
											"orig": "kind",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "limit",
											"orig": "limit",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "limit_from",
											"orig": "limit_from",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "min_dist_max",
											"orig": "min_dist_max",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "min_dist_min",
											"orig": "min_dist_min",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "nea",
											"orig": "nea",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "nea_comet",
											"orig": "nea_comet",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": true,
											"kind": "query",
											"name": "neo",
											"orig": "neo",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "pha",
											"orig": "pha",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"example": "date",
											"kind": "query",
											"name": "sort",
											"orig": "sort",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": 2000433,
											"kind": "query",
											"name": "spk",
											"orig": "spk",
											"reqd": false,
											"type": "`$INTEGER`",
											"active": true,
										},
										map[string]any{
											"example": false,
											"kind": "query",
											"name": "total_only",
											"orig": "total_only",
											"reqd": false,
											"type": "`$BOOLEAN`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "v_inf_max",
											"orig": "v_inf_max",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "v_inf_min",
											"orig": "v_inf_min",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "v_rel_max",
											"orig": "v_rel_max",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "v_rel_min",
											"orig": "v_rel_min",
											"reqd": false,
											"type": "`$NUMBER`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/cad.api",
								"parts": []any{
									"cad.api",
								},
								"select": map[string]any{
									"exist": []any{
										"body",
										"class",
										"comet",
										"date_max",
										"date_min",
										"des",
										"diameter",
										"dist_max",
										"dist_min",
										"fullname",
										"h_max",
										"h_min",
										"kind",
										"limit",
										"limit_from",
										"min_dist_max",
										"min_dist_min",
										"nea",
										"nea_comet",
										"neo",
										"pha",
										"sort",
										"spk",
										"total_only",
										"v_inf_max",
										"v_inf_min",
										"v_rel_max",
										"v_rel_min",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
