# CloseApproachData SDK configuration


def make_config():
    return {
        "main": {
            "name": "CloseApproachData",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://ssd-api.jpl.nasa.gov",
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "cadapi": {},
            },
        },
        "entity": {
      "cadapi": {
        "fields": [
          {
            "active": True,
            "name": "count",
            "req": True,
            "type": "`$NUMBER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "data",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "fields",
            "req": False,
            "type": "`$ARRAY`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "signature",
            "req": True,
            "type": "`$OBJECT`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "total",
            "req": False,
            "type": "`$NUMBER`",
            "index$": 4,
          },
        ],
        "name": "cadapi",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "example": "Earth",
                      "kind": "query",
                      "name": "body",
                      "orig": "body",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "ATE",
                      "kind": "query",
                      "name": "class",
                      "orig": "class",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "comet",
                      "orig": "comet",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "2100-01-01",
                      "kind": "query",
                      "name": "date_max",
                      "orig": "date_max",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "2018-01-01",
                      "kind": "query",
                      "name": "date_min",
                      "orig": "date_min",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "433",
                      "kind": "query",
                      "name": "des",
                      "orig": "des",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "diameter",
                      "orig": "diameter",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "0.2",
                      "kind": "query",
                      "name": "dist_max",
                      "orig": "dist_max",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "0.05",
                      "kind": "query",
                      "name": "dist_min",
                      "orig": "dist_min",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "fullname",
                      "orig": "fullname",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "h_max",
                      "orig": "h_max",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "h_min",
                      "orig": "h_min",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "kind",
                      "orig": "kind",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "limit",
                      "orig": "limit",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "limit_from",
                      "orig": "limit_from",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "min_dist_max",
                      "orig": "min_dist_max",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "min_dist_min",
                      "orig": "min_dist_min",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "nea",
                      "orig": "nea",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "nea_comet",
                      "orig": "nea_comet",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": True,
                      "kind": "query",
                      "name": "neo",
                      "orig": "neo",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "pha",
                      "orig": "pha",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "date",
                      "kind": "query",
                      "name": "sort",
                      "orig": "sort",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": 2000433,
                      "kind": "query",
                      "name": "spk",
                      "orig": "spk",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "total_only",
                      "orig": "total_only",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "v_inf_max",
                      "orig": "v_inf_max",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "v_inf_min",
                      "orig": "v_inf_min",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "v_rel_max",
                      "orig": "v_rel_max",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "v_rel_min",
                      "orig": "v_rel_min",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                  ],
                },
                "kind": "http",
                "method": "GET",
                "orig": "/cad.api",
                "parts": [
                  "cad.api",
                ],
                "select": {
                  "exist": [
                    "body",
                    "class",
                    "comet",
                    "date_max",
                    "date_min",
                    "des",
                    "diameter",
                    "dist_max",
                    "dist_min",
                    "fullname",
                    "h_max",
                    "h_min",
                    "kind",
                    "limit",
                    "limit_from",
                    "min_dist_max",
                    "min_dist_min",
                    "nea",
                    "nea_comet",
                    "neo",
                    "pha",
                    "sort",
                    "spk",
                    "total_only",
                    "v_inf_max",
                    "v_inf_min",
                    "v_rel_max",
                    "v_rel_min",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
